apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ems-app-svc-mon
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: ems-app-svc
  namespaceSelector:
    matchNames:
      - ENV_NAME
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mariadb-exporter-svc-mon
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: mariadb-exporter
  namespaceSelector:
    matchNames:
      - ENV_NAME
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s