apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ems-app-svc-mon
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: ems-app
  namespaceSelector:
    matchNames:
      - ENV_NAME
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mariadb-svc-mon
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: mariadb
  namespaceSelector:
    matchNames:
      - ENV_NAME
  endpoints:
    - port: metrics
      interval: 30s